export CARDANO_NODE_SOCKET_PATH="/home/cardano/cardano-node/db/socket"
export CARDANO_NODE_CONFIG_PATH="/home/cardano/cardano-node/configuration/config.json"
export OGMIOS_HOST="127.0.0.1"
export OGMIOS_PORT="1337"
export MUESLISWAP_KUPO="/path/to/muesliswap_kupo"